services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    restart: always
    labels:
      - db
      - postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT} #5432
    shm_size: 256mb
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 268435456 #256*2^20=268435456
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      start_period: 10s
      interval: 3s
      timeout: 2s
      retries: 10
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
    labels:
      - db
      - postgres

volumes:
  postgres-data:
    driver: local
    labels:
      - db
      - postgres